server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    mongodb:
      database: kstadium_main
      url: mongodb://${dev_mongo_username:a}:${dev_mongo_password:a}@${dev_mongo_url:localhost:27017}?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      username: ${dev_mongo_username:a}
      password: ${dev_mongo_password:a}
    ksmain:
      url: jdbc:mysql://${dev_mysql_url:localhost:3306}/kstadium_main?characterEncoding=utf8&allowMultiQueries=true
      username: ${dev_mysql_username:a}
      password: ${dev_mysql_password:a}
      driver-class-name: com.mysql.cj.jdbc.Driver
      validationQuery: SELECT 1
      poolName: Mysqldb-HikariCP-Main
      maxPoolSize: 100
      leakDetectionThreshold: 30000
    kstadium-web-db:
      url: jdbc:mysql://${dev_mysql_url:localhost:3306}/kstadium_web_db?characterEncoding=utf8&allowMultiQueries=true
      username: ${dev_mysql_username:a}
      password: ${dev_mysql_password:a}
      driver-class-name: com.mysql.cj.jdbc.Driver
      validationQuery: SELECT 1
      poolName: Mysqldb-HikariCP-Sub
      maxPoolSize: 100
      leakDetectionThreshold: 30000

mongo:
  ssl:
    trustStore: classpath:cert/dev/rds-truststore.jks
    trustStorePassword: ${dev_trustStorePassword:a}

kstadium:
  api:
    ground-chain-service: https://gnd-api.dev.kstadium.io
  time: 9
---
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    mongodb:
      database: kstadium_main
      url: mongodb://${stg_mongo_username:a}:${stg_mongo_password:a}@${stg_mongo_url:localhost:27017}?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      username: ${stg_mongo_username:a}
      password: ${stg_mongo_password:a}
    ksmain:
      url: jdbc:mysql://${stg_mysql_url:localhost:3306}/kstadium_main?characterEncoding=utf8&allowMultiQueries=true
      username: ${stg_mysql_username:a}
      password: ${stg_mysql_password:a}
      driver-class-name: com.mysql.cj.jdbc.Driver
      validationQuery: SELECT 1
      poolName: Mysqldb-HikariCP-Main
      maxPoolSize: 100
      leakDetectionThreshold: 30000
    kstadium-web-db:
      url: jdbc:mysql://${stg_mysql_url:localhost:3306}/kstadium_web_db?characterEncoding=utf8&allowMultiQueries=true
      username: ${stg_mysql_username:a}
      password: ${stg_mysql_password:a}
      driver-class-name: com.mysql.cj.jdbc.Driver
      validationQuery: SELECT 1
      poolName: Mysqldb-HikariCP-Sub
      maxPoolSize: 100
      leakDetectionThreshold: 30000

mongo:
  ssl:
    trustStore: classpath:cert/stage/rds-truststore.jks
    trustStorePassword: ${stg_trustStorePassword:a}

kstadium:
  api:
    ground-chain-service: https://gnd-api.stg.kstadium.io
  time: 9
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    mongodb:
      database: kstadium_main
      url: mongodb://${prd_mongo_username:a}:${prd_mongo_password:a}@${prd_mongo_url:localhost:27017}?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      username: ${prd_mongo_username:a}
      password: ${prd_mongo_password:a}
    ksmain:
      url: jdbc:mysql://${prd_mysql_url:localhost:3306}/kstadium_main?characterEncoding=utf8&allowMultiQueries=true
      username: ${prd_mysql_username:a}
      password: ${prd_mysql_password:a}
      driver-class-name: com.mysql.cj.jdbc.Driver
      validationQuery: SELECT 1
      poolName: Mysqldb-HikariCP-Main
      maxPoolSize: 100
      leakDetectionThreshold: 30000
    kstadium-web-db:
      url: jdbc:mysql://${prd_mysql_url:localhost:3306}/kstadium_web_db?characterEncoding=utf8&allowMultiQueries=true
      username: ${prd_mysql_username:a}
      password: ${prd_mysql_password:a}
      driver-class-name: com.mysql.cj.jdbc.Driver
      validationQuery: SELECT 1
      poolName: Mysqldb-HikariCP-Sub
      maxPoolSize: 100
      leakDetectionThreshold: 30000

mongo:
  ssl:
    trustStore: classpath:cert/prod/rds-truststore.jks
    trustStorePassword: ${prd_trustStorePassword:a}

kstadium:
  api:
    ground-chain-service: https://gnd-api.kstadium.io
  time: 9
---